blank_issues_enabled: false
contact_links:    
  - name: ğŸ†˜ Storyblok Livechat - the quickest way to get help
    url: https://www.storyblok.com/
    about: Communicate directly with our support team using the chat-chat widget on our website.
  
  - name: ğŸ› Storyblok Helpdesk
    url: https://storyblok.atlassian.net/servicedesk/customer/portals
    about: The easiest way to report bugs and raise your questions.
    
  - name: ğŸ‘©â€ğŸš€ Discord community
    url: https://discord.gg/WmMYYQp
    about: Discuss your challenges with our growing community of superb developers and ambassadors.
    
  - name: Feature idea?
    url: https://www.storyblok.com/faq/How-to-report-bugs-and-request-features-on-storyblok
    about: Find out why we temporarily paused public feature requests.
