blank_issues_enabled: false
contact_links:    
  - name: ğŸ› Storyblok Helpdesk
    url: https://support.storyblok.com
    about: The easiest way to report bugs and raise your questions. SSO login with your Storyblok account.
    
  - name: ğŸ‘©â€ğŸš€ Discord community
    url: https://discord.gg/WmMYYQp
    about: Discuss your challenges with our growing community of superb developers and ambassadors.
    
  - name: Feature idea?
    url: https://www.storyblok.com/faq/How-to-report-bugs-and-request-features-on-storyblok
    about: Find out why we temporarily paused public feature requests.
